// <auto-generated />
namespace DataLayerContext.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddCounties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCounties));
        
        string IMigrationMetadata.Id
        {
            get { return "201308261503559_AddCounties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
