//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendlyForms.CardSafe {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pmn.payment-gate.net/ws/", ConfigurationName="CardSafe.CardSafeSoap")]
    public interface CardSafeSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmn.payment-gate.net/ws/StoreCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FriendlyForms.CardSafe.Response StoreCard(string UserName, string Password, string TokenMode, string CardNum, string ExpDate, string CustomerKey, string NameOnCard, string Street, string Zip, string ExtData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmn.payment-gate.net/ws/StoreCard", ReplyAction="*")]
        System.Threading.Tasks.Task<FriendlyForms.CardSafe.Response> StoreCardAsync(string UserName, string Password, string TokenMode, string CardNum, string ExpDate, string CustomerKey, string NameOnCard, string Street, string Zip, string ExtData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmn.payment-gate.net/ws/ProcessCreditCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FriendlyForms.CardSafe.Response ProcessCreditCard(string UserName, string Password, string TransType, string CardToken, string TokenMode, string Amount, string InvNum, string PNRef, string ExtData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://pmn.payment-gate.net/ws/ProcessCreditCard", ReplyAction="*")]
        System.Threading.Tasks.Task<FriendlyForms.CardSafe.Response> ProcessCreditCardAsync(string UserName, string Password, string TransType, string CardToken, string TokenMode, string Amount, string InvNum, string PNRef, string ExtData);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18058")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pmn.payment-gate.net/ws/")]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultField;
        
        private string respMSGField;
        
        private string messageField;
        
        private string message1Field;
        
        private string message2Field;
        
        private string authCodeField;
        
        private string pNRefField;
        
        private string hostCodeField;
        
        private string hostURLField;
        
        private string receiptURLField;
        
        private string getAVSResultField;
        
        private string getAVSResultTXTField;
        
        private string getStreetMatchTXTField;
        
        private string getZipMatchTXTField;
        
        private string getCVResultField;
        
        private string getCVResultTXTField;
        
        private string getGetOrigResultField;
        
        private string getCommercialCardField;
        
        private string workingKeyField;
        
        private string keyPointerField;
        
        private string extDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RespMSG {
            get {
                return this.respMSGField;
            }
            set {
                this.respMSGField = value;
                this.RaisePropertyChanged("RespMSG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Message1 {
            get {
                return this.message1Field;
            }
            set {
                this.message1Field = value;
                this.RaisePropertyChanged("Message1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Message2 {
            get {
                return this.message2Field;
            }
            set {
                this.message2Field = value;
                this.RaisePropertyChanged("Message2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AuthCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
                this.RaisePropertyChanged("AuthCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PNRef {
            get {
                return this.pNRefField;
            }
            set {
                this.pNRefField = value;
                this.RaisePropertyChanged("PNRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string HostCode {
            get {
                return this.hostCodeField;
            }
            set {
                this.hostCodeField = value;
                this.RaisePropertyChanged("HostCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string HostURL {
            get {
                return this.hostURLField;
            }
            set {
                this.hostURLField = value;
                this.RaisePropertyChanged("HostURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ReceiptURL {
            get {
                return this.receiptURLField;
            }
            set {
                this.receiptURLField = value;
                this.RaisePropertyChanged("ReceiptURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string GetAVSResult {
            get {
                return this.getAVSResultField;
            }
            set {
                this.getAVSResultField = value;
                this.RaisePropertyChanged("GetAVSResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string GetAVSResultTXT {
            get {
                return this.getAVSResultTXTField;
            }
            set {
                this.getAVSResultTXTField = value;
                this.RaisePropertyChanged("GetAVSResultTXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string GetStreetMatchTXT {
            get {
                return this.getStreetMatchTXTField;
            }
            set {
                this.getStreetMatchTXTField = value;
                this.RaisePropertyChanged("GetStreetMatchTXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string GetZipMatchTXT {
            get {
                return this.getZipMatchTXTField;
            }
            set {
                this.getZipMatchTXTField = value;
                this.RaisePropertyChanged("GetZipMatchTXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string GetCVResult {
            get {
                return this.getCVResultField;
            }
            set {
                this.getCVResultField = value;
                this.RaisePropertyChanged("GetCVResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string GetCVResultTXT {
            get {
                return this.getCVResultTXTField;
            }
            set {
                this.getCVResultTXTField = value;
                this.RaisePropertyChanged("GetCVResultTXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string GetGetOrigResult {
            get {
                return this.getGetOrigResultField;
            }
            set {
                this.getGetOrigResultField = value;
                this.RaisePropertyChanged("GetGetOrigResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string GetCommercialCard {
            get {
                return this.getCommercialCardField;
            }
            set {
                this.getCommercialCardField = value;
                this.RaisePropertyChanged("GetCommercialCard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string WorkingKey {
            get {
                return this.workingKeyField;
            }
            set {
                this.workingKeyField = value;
                this.RaisePropertyChanged("WorkingKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string KeyPointer {
            get {
                return this.keyPointerField;
            }
            set {
                this.keyPointerField = value;
                this.RaisePropertyChanged("KeyPointer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ExtData {
            get {
                return this.extDataField;
            }
            set {
                this.extDataField = value;
                this.RaisePropertyChanged("ExtData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CardSafeSoapChannel : FriendlyForms.CardSafe.CardSafeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CardSafeSoapClient : System.ServiceModel.ClientBase<FriendlyForms.CardSafe.CardSafeSoap>, FriendlyForms.CardSafe.CardSafeSoap {
        
        public CardSafeSoapClient() {
        }
        
        public CardSafeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CardSafeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardSafeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CardSafeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FriendlyForms.CardSafe.Response StoreCard(string UserName, string Password, string TokenMode, string CardNum, string ExpDate, string CustomerKey, string NameOnCard, string Street, string Zip, string ExtData) {
            return base.Channel.StoreCard(UserName, Password, TokenMode, CardNum, ExpDate, CustomerKey, NameOnCard, Street, Zip, ExtData);
        }
        
        public System.Threading.Tasks.Task<FriendlyForms.CardSafe.Response> StoreCardAsync(string UserName, string Password, string TokenMode, string CardNum, string ExpDate, string CustomerKey, string NameOnCard, string Street, string Zip, string ExtData) {
            return base.Channel.StoreCardAsync(UserName, Password, TokenMode, CardNum, ExpDate, CustomerKey, NameOnCard, Street, Zip, ExtData);
        }
        
        public FriendlyForms.CardSafe.Response ProcessCreditCard(string UserName, string Password, string TransType, string CardToken, string TokenMode, string Amount, string InvNum, string PNRef, string ExtData) {
            return base.Channel.ProcessCreditCard(UserName, Password, TransType, CardToken, TokenMode, Amount, InvNum, PNRef, ExtData);
        }
        
        public System.Threading.Tasks.Task<FriendlyForms.CardSafe.Response> ProcessCreditCardAsync(string UserName, string Password, string TransType, string CardToken, string TokenMode, string Amount, string InvNum, string PNRef, string ExtData) {
            return base.Channel.ProcessCreditCardAsync(UserName, Password, TransType, CardToken, TokenMode, Amount, InvNum, PNRef, ExtData);
        }
    }
}
